### ISSUE TITLE
linux release wont run

### ISSUE THREAD

**Issue by Andy16k** [numerarecoin/numerare-core#1]
libboost_system.so.1.58.0: cannot open shared object file: no such file or directory

**Comment by Andy16k** [comment]
Yeah tried that already
Still doesn't work



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by M4iKZ** [comment]
What distro do you use?

**Comment by Andy16k** [comment]
Ubuntu 16.4 something, the desktop version



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Andy16k** [comment]
It's showing as 1.62



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by M4iKZ** [comment]
I think that you have two possibility:
recompile from source with boost 1.62 or remove boost lib and install the older 1.58.
`sudo apt remove libboost-all-dev`
`sudo apt install libboost1.58-all-dev`

let me know if this fix your issue ;)

**Comment by Andy16k** [comment]
Cool
I'll give it a try when I get home

Is this coin currently on test net, wasn't completely sure where it said pre-release

Thank you
Andy


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by M4iKZ** [comment]
join in discord soon will release the seed
