### ISSUE TITLE
gets stuck

### ISSUE THREAD

**Issue by Andy16k** [numerarecoin/numerare-core#2]
2018-May-07 08:16:48.391750 INFO    numerare v0.0.1.5t (Libertas)
2018-May-07 08:16:48.391994 INFO    Module folder: numerared
2018-May-07 08:16:48.392131 INFO    Opening DB in /home/andy/.numerare/DB
2018-May-07 08:16:48.403111 INFO    DB opened in /home/andy/.numerare/DB
2018-May-07 08:16:48.403291 INFO    Initializing core...
2018-May-07 08:16:48.404246 INFO    Core initialized OK
2018-May-07 08:16:48.404314 INFO    Initializing p2p server...
2018-May-07 08:16:48.404382 INFO    Binding on 0.0.0.0:19131
2018-May-07 08:16:48.404452 INFO    Net service binded on 0.0.0.0:19131
2018-May-07 08:16:48.404495 INFO    Attempting to add IGD port mapping.
2018-May-07 08:16:52.441638 INFO    No IGD was found.
2018-May-07 08:16:52.441728 INFO    P2p server initialized OK
2018-May-07 08:16:52.441893 INFO    Starting core rpc server on address 127.0.0.1:13191
2018-May-07 08:16:52.441965 INFO    Core rpc server started ok
2018-May-07 08:16:52.442004 INFO    Starting p2p net loop...
2018-May-07 08:16:52.442028 INFO    Starting node_server

thats as far as itll go, then it just stays there

**Comment by M4iKZ** [comment]
Missing the peer into the code, this week we will realeased an updated version
